CREATE TABLE MATCH_POST (
    MATCH_IDX INT(10) PRIMARY KEY,
    WRITER INT(10),
    MATCH_DATE DATE NOT NULL,
    MATCH_TIME VARCHAR(5) NOT NULL,
    PLAYER_MAX INT(2) NOT NULL,
    PLAYER_MIN INT(2) NOT NULL,
    PLAYER_GENDER CHAR(1) NOT NULL,
    PRICE INT(10) NOT NULL,
    REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- FOREIGN KEY (WRITER) REFERENCES BUSINESS_USER(BUSINESS_IDX) ON DELETE CASCADE

select * from MATCH_POST;