CREATE TABLE MATCH_POST (
    MATCH_IDX INT(10) AUTO_INCREMENT PRIMARY KEY,
    WRITER INT(10),
    MATCH_DATE DATE NOT NULL,
    MATCH_TIME VARCHAR(10) NOT NULL,
    PLAYER_MAX INT(2) NOT NULL,
    PLAYER_MIN INT(2) NOT NULL,
    PLAYER_GENDER CHAR(1) NOT NULL,
    MATCH_LEVEL VARCHAR(10) NOT NULL,
    TEAM_STYLE VARCHAR(15) NOT NULL,
    PRICE INT(10) NOT NULL,
    REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- FOREIGN KEY (WRITER) REFERENCES BUSINESS_USER(BUSINESS_IDX) ON DELETE CASCADE

select * from MATCH_POST;
delete from MATCH_POST;
drop table MATCH_POST;
