CREATE TABLE PAYMENT_HISTORY (
     PAYMENT_HISTORY_IDX INT AUTO_INCREMENT PRIMARY KEY,
     PAYMENT_IDX INT NOT NULL,
     PAYMENT_STATUS VARCHAR(10) NOT NULL,
     ACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     MERCHANT_UID VARCHAR(30) NOT NULL
);


# 자동 payment_idx update
DELIMITER $$

CREATE TRIGGER update_payment_idx_in_history
    AFTER INSERT ON PAYMENT
    FOR EACH ROW
BEGIN
    UPDATE PAYMENT_HISTORY
    SET PAYMENT_IDX = NEW.PAYMENT_IDX
    WHERE MERCHANT_UID = NEW.MERCHANT_UID;
END $$

DELIMITER ;

SHOW TRIGGERS;


select * from PAYMENT_HISTORY;
