CREATE TABLE PAYMENT_HISTORY (
     PAYMENT_HISTORY_IDX INT AUTO_INCREMENT PRIMARY KEY,
     ACTION_TYPE VARCHAR(50) NOT NULL,
     PAYMENT_REFUND_IDX INT NOT NULL,
     IMP_UID VARCHAR(255) NOT NULL,
     MERCHANT_UID VARCHAR(255) NOT NULL,
     MATCH_IDX INT NOT NULL,
     SELLER_IDX INT NOT NULL,
     BUYER_IDX INT NOT NULL,
     PAYMENT_REFUND_AMOUNT DECIMAL(10, 2) NOT NULL,
     PAYMENT_REFUND_METHOD VARCHAR(50) NOT NULL,
     PAYMENT_REFUND_DATE TIMESTAMP NOT NULL,
     ACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

# 결제정보 저장 트리거
CREATE TRIGGER after_payment_insert
    AFTER INSERT ON PAYMENT
    FOR EACH ROW
BEGIN
    INSERT INTO PAYMENT_HISTORY (
        ACTION_TYPE,
        PAYMENT_REFUND_IDX,
        IMP_UID,
        MERCHANT_UID,
        MATCH_IDX,
        SELLER_IDX,
        BUYER_IDX,
        PAYMENT_REFUND_AMOUNT,
        PAYMENT_REFUND_METHOD,
        PAYMENT_REFUND_DATE,
        ACTION_DATE
    )
    VALUES (
               'Payment',
               NEW.PAYMENT_IDX,
               NEW.IMP_UID,
               NEW.MERCHANT_UID,
               NEW.MATCH_IDX,
               NEW.SELLER_IDX,
               NEW.BUYER_IDX,
               NEW.PAYMENT_AMOUNT,
               NEW.PAYMENT_METHOD,
               NEW.PAYMENT_DATE,
               CURRENT_TIMESTAMP
           );
END;




select * from PAYMENT_HISTORY;
