CREATE TABLE REFUND (
    REFUND_IDX INT AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_IDX INT NOT NULL,
    MATCH_IDX INT NOT NULL,
    BUYER_IDX INT NOT NULL,
    SELLER_IDX INT NOT NULL,
    REFUND_METHOD VARCHAR(100) NOT NULL,
    REFUND_AMOUNT DECIMAL(10, 2) NOT NULL,
    REFUND_REASON VARCHAR(100) NOT NULL,
    REFUND_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MERCHANT_UID VARCHAR(30) NOT NULL,
    IMP_UID VARCHAR(30) NOT NULL
);

select * from REFUND;